function debug_exp

  bestConfigs = {} ;
  oo.sharedX0 = [] ; % can be used for direct comparison
  oo.randScale = 1 ;
  oo.x0noise = 0.5 ;
  oo.numIters = 20 ;
  oo.numRepeats = 1 ;
  oo.addNoise = false ;
  %oo.dataset = 'rosenbrock' ;
  oo.dataset = 'rahimi-recht' ;

  % start at a lower level
  %compare_solvers('expType', 'repeated-runs', ...
  %compare_solvers('expType', 'blend', ...
  compare_solvers('expType', 'curveball-only', ...
                  'addNoise', oo.addNoise, ...
                  'randScale', oo.randScale, ...
                  'bestConfigs', bestConfigs, ...
                  'numIters', oo.numIters, ...
                  'sharedX0', oo.sharedX0, ...
                  'x0noise', oo.x0noise, ...
                  'numRepeats', oo.numRepeats, ...
                  'experiment', oo.dataset ...
                  ) ;

  %paper_exp('setting', 'dev', ...
            %'refreshRepeats', 1, ...
            %'numRepeats', 1, ...
            %'numIters', 2, ...
            %'tolerance', 0.0001, ...
            %'dataset', 'rosenbrock', ...
            %'refreshGrid', true, ...
            %'addNoise', 0) ;
