function solverConfigs = standardConfigs(problemName, expType, varargin)
%STANDARDCONFIGS - stores solver configurations for experiments
%   SOLVERCONFIGS = STANDARDCONFIGS(PROBLEMNAME, EXPTYPE, VARARGIN)
%   stores a collection of solver configurations. This is primarily
%   useful for producing comparisons bewtween solvers, since it takes
%   some effort to work out a reasonable set of parameters for each
%   solver on each particular problem.
%
%   SOLVERCONFIGS(..., 'option', value, ...) accepts the following
%   options:
%
%   `bestConfigs`:: {}
%    An array of custom experimental configurations. This option is
%    useful when the best configruations have already been found by
%    grid search and the goal is to use resulting hyperparameters
%    for an experiment.
%
% Copyright (C) 2018 Samuel Albanie
% Licensed under The MIT License [see LICENSE.md for details]

  opts.bestConfigs = {} ;
  opts = vl_argparse(opts, varargin) ;

  % These options seem to work fine with Curveball, but there may
  % be better combinations. Documentation for the parameters can
  % be found via running `help CurveBall`.
  hyenalOpts = {'autoparam', true, ...
                'momentum', 0.95, ...
                'beta', 0.005, ...
                'autolambda', false} ; % only supported for classification

  switch problemName
    case 'rahimiRecht'
      hyenalOpts = [hyenalOpts {'lambda', 1, 'learningRate', 1}] ;
    case 'rosenbrock'
      hyenalOpts = [hyenalOpts {'lambda', 1E-1, 'learningRate', 5E-1}] ;
  end

  switch expType
    case 'blend'
      solverConfigs = { ...
        {'name', 'SGD', 'learningRate', 1e-3, 'momentum', 0.9}, ...
        {'name', 'LM'}, ...
        {'name', 'BFGS'}, ...
        [{'name', 'CurveBall'}, hyenalOpts], ...
      } ;
    case 'sgd-only'
      solverConfigs = { ...
        {'name', 'SGD', 'learningRate', 1e-3, 'momentum', 0.9}, ...
      } ;
    case 'curveball-only'
      solverConfigs = { ...
        [{'name', 'CurveBall'}, hyenalOpts], ...
      } ;
    case 'builtin-check'
      solverConfigs = { ...
        {'name', 'LM'}, ...
        {'name', 'BFGS'}, ...
      } ;
    case 'grid-search'
      required = {'gridLearningRates', 'gridRhos', 'gridMomentums', ...
                  'gridBeta1s', 'gridBeta2s'} ;
      for ii = 1:numel(required)
        assert(~isempty(oo.(required{ii})), ...
                'grid search:%s  should be set explicityly', required{ii}) ;
      end
      solverConfigs = { ...
        {'name', 'SGD', 'learningRate', oo.gridLearningRates, ...
                        'momentum', oo.gridMomentums}, ...
        {'name', 'Adam', ...
         'learningRate', oo.gridLearningRates, ...
         'beta1'  oo.gridBeta1s, ...
         'beta2', oo.gridBeta2s}, ...
        {'name', 'LM'}, ...
        {'name', 'BFGS'}, ...
        [{'name', 'CurveBall'}, hyenalOpts], ...
      } ;
    case 'repeated-runs'
      assert(~isempty(opts.bestConfigs), 'bestConfigs must be specified') ;
      solverConfigs = cellfun(@(x) [x {'numRepeats', oo.numRepeats}], ...
                                       opts.bestConfigs, 'uni', 0) ;
    otherwise, error('unrecognised expType setting: %d\n', expType) ;
  end
